# Generated by Django 4.2.6 on 2023-12-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_prop_profile_id_cop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_cop',
            new_name='id_prop',
        ),
    ]
