# Generated by Django 4.2.6 on 2023-12-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_id_cop_profile_id_prop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_prop',
            new_name='id_cop',
        ),
    ]
