# Generated by Django 4.2.6 on 2023-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_id_prop_profile_id_cop'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
