# Generated by Django 4.2.6 on 2024-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('proprietaire', 'proprietaire'), ('syndic', 'syndic')], max_length=15),
        ),
    ]
