# Generated by Django 4.2.6 on 2023-12-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copropriete',
            fields=[
                ('id_cop', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('nb_props', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id_cot', models.AutoField(primary_key=True, serialize=False)),
                ('type_cot', models.CharField(choices=[('Normale', 'Normale'), ('Business', 'Business'), ('Exceptionnelle', 'Exceptionnelle')], max_length=30)),
                ('montant', models.FloatField()),
                ('date_creation', models.DateField()),
                ('id_cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.copropriete')),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id_prop', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=10)),
                ('occupation', models.BooleanField(default=False)),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.copropriete')),
                ('id_cot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.cotisation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_pay', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('date_creation', models.DateField()),
                ('date_paiement', models.DateField()),
                ('etat', models.BooleanField(default=False)),
                ('id_cot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.cotisation')),
                ('id_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_docu', models.AutoField(primary_key=True, serialize=False)),
                ('nomdoc', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('id_cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.copropriete')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id_depense', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('Assainissement', 'Assainissement'), ('Maintenance et reparation', 'Maintenance et reparation'), ('Matériel', 'Matériel'), ('Gardiennage', 'Gardiennage'), ('Autre', 'Autre')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('montant', models.FloatField()),
                ('date_dep', models.DateField()),
                ('id_cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.copropriete')),
            ],
        ),
    ]
