# Generated by Django 4.2.3 on 2023-12-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_alter_paiement_date_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriete',
            old_name='CIN',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='depense',
            name='nomDep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
