# Generated by Django 4.2.6 on 2023-12-23 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interfaces', '0003_rename_cin_propriete_id_user_depense_nomdep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='id_cot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interfaces.cotisation'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
