# Generated by Django 4.2.3 on 2024-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_alter_propriete_id_cot_alter_propriete_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriete',
            name='statut',
            field=models.CharField(choices=[('propritaire', 'proprietaire'), ('locataire', 'locataire')], default='proprietaire', max_length=30),
        ),
    ]
