# Generated by Django 4.2.6 on 2024-02-08 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interfaces', '0005_alter_propriete_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriete',
            name='statut',
            field=models.CharField(choices=[('propritaire', 'proprietaire'), ('locataire', 'locataire')], default='proprietaire', max_length=30),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
