# Generated by Django 4.2.3 on 2024-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_depense_visible_propriete_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='mail_envoye',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
